modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dark_portal_tools"
version="1.0.0"
displayName="Dark Portal Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ShishKebab, MCreator"

[[dependencies.dark_portal_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




